### ISSUE TITLE
💡 Setup Stream Deck to switch screen input sources

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/configs-homelab#17]
- A script on machine `caprica` should be called with a param from the Stream Deck
- Param-Set 1 to switch to `caprica`
- Param-Set 2 to switch to work machine

### Todo
- [ ] Jarvis already knows how to do this. Turn into dedcicated script in configs-homelab repo (maybe a dedicated `stream-deck` component)
- [ ] Document this setup
- [ ] Configure Stream Deck
- [ ] https://github.com/sommerfeld-io/configs-homelab/issues/11

```ditaa

+------------------------+
|  caprica               |
|                        |
|    +--------------+    |
|    |     bash     |    |
|    |    script    |    |
|    +--------------+    |
|        ^      ^        |
|        |      |        |
+--------|------|--------+
         |      |
         |      |
   param |      | param
screen 1 |      | screen 2
         |      |
+--------|------|--------+
|        |      |        |
|      +-+-+  +-+-+      |
|      |   |  |   |      |
|      +---+  +---+      |
|                        |
|  stream deck           |
+------------------------+

```
